"use client"

import { useState } from "react"
import { Check, Globe, Link2, Unplug } from "lucide-react"
import { Sidebar } from "@/components/sidebar"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

const platforms = [{ name: "Instagram", handle: "@reelstudio_ig", color: "text-pink-500", connected: true }, { name: "YouTube", handle: "@reelstudio", color: "text-red-500", connected: true }, { name: "Facebook", handle: "@reelstudio.fb", color: "text-blue-500", connected: true }, { name: "TikTok", handle: "", color: "text-foreground", connected: false }, { name: "X", handle: "@reelstudio_x", color: "text-foreground", connected: true }]
export default function PlatformsPage() { const [state, setState] = useState(platforms); return <div className="min-h-screen bg-background"><Sidebar initialActive="platforms" /><div className="lg:pl-60"><header className="border-b border-border bg-card px-6 py-5 lg:px-8"><h1 className="text-xl font-semibold">Connected Platforms</h1><p className="text-sm text-muted-foreground">Manage where your videos are published</p></header><main className="mx-auto flex max-w-5xl flex-col gap-6 px-6 py-6 lg:px-8"><div className="grid gap-4 md:grid-cols-2">{state.map((platform) => <Card key={platform.name}><CardHeader className="flex flex-row items-start justify-between"><div className="flex items-center gap-3"><div className={`flex size-10 items-center justify-center rounded-lg border border-border bg-muted font-bold ${platform.color}`}>{platform.name.slice(0, 2)}</div><div><CardTitle className="text-base">{platform.name}</CardTitle><p className="text-sm text-muted-foreground">{platform.handle || "No account connected"}</p></div></div><span className={`flex items-center gap-1 text-xs ${platform.connected ? "text-emerald-600" : "text-muted-foreground"}`}><span className={`size-1.5 rounded-full ${platform.connected ? "bg-emerald-500" : "bg-muted-foreground"}`} />{platform.connected ? "Connected" : "Disconnected"}</span></CardHeader><CardContent className="flex flex-col gap-4"><p className="text-xs leading-5 text-muted-foreground">{platform.connected ? "Publish videos · Read insights · Manage profile" : "Connect your account to publish automatically."}</p><Button variant={platform.connected ? "outline" : "default"} onClick={() => setState((items) => items.map((item) => item.name === platform.name ? { ...item, connected: !item.connected, handle: item.connected ? "" : `@${item.name.toLowerCase()}_studio` } : item))}>{platform.connected ? <><Unplug data-icon="inline-start" />Disconnect</> : <><Link2 data-icon="inline-start" />Connect account</>}</Button></CardContent></Card>)}</div><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Globe className="size-4 text-primary" />How platform connections work</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">ReelAgent uses a secure, one-time OAuth setup to connect your publishing accounts. We only request the permissions needed to upload content and read performance insights. You can disconnect any account at any time.</p><div className="mt-4 flex items-center gap-2 text-sm text-emerald-600"><Check className="size-4" />Your credentials are never stored in ReelAgent</div></CardContent></Card></main></div></div> }
